apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hpa-admission-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hpa-admission-controller
    spec:
      serviceAccountName: hpa-admission-controller
      containers:
      - name: hpa-admission-controller
        image: gcr.io/aleksandram-public-images/hpa-admission-controller:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: tls-certs
            mountPath: "/etc/tls-certs"
            readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 8000
      volumes:
        - name: tls-certs
          secret:
            secretName: hpa-tls-certs
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-webhook
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: hpa-admission-controller
