apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-webhook
  namespace: kube-system
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hpa-webhook
  metrics:
  - type: External
    external:
      metricName: "queue/messages/ready"
      metricSelector:
        matchLabels:
          queue: worker_tasks
      targetAverageValue: 30
